/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thesis.vault;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;


public class App {

    public static void main(String[] args) {

        File mainDirectory = new File(args[0]);
        AppHelper helper = new AppHelper(".java");

        if (mainDirectory.exists() && mainDirectory.isDirectory()) {

            // array for files and sub-directories
            // of directory pointed by mainDirectory
            File arr[] = mainDirectory.listFiles();

            try {
                StringBuilder logSb = new StringBuilder();
                PrintWriter logPw = new PrintWriter("log.txt");
                logSb.append("**********************************************\n")
                    .append("Files from main directory : ").append(mainDirectory).append("\n")
                    .append("**********************************************\n");

                // Calling recursive method
                helper.retrieveAllFiles(arr, 0, 0, logSb);
                logPw.print(logSb);
                logPw.flush();
                logPw.close();

            } catch (FileNotFoundException e) {
                System.out.println(e);
            }
        }
    }
}
